config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :contacts, only: [:create]
  resources :announcements, only: %i[index show]
  resources :events, only: %i[index show] do
    member do
      post 'join'
      post 'quit'
      get 'participants'
    end
  end
  get 'index', 'term', 'about', 'contact', controller: 'pages'
  namespace :account do
    resource :profile, except: [:destroy]
    resource :subscription, only: [:show, :edit, :update]
    resources :messengers, only: [:update]
    resources :events, only: [:index]
  end
  # custom devise controllers
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    delete 'users/unconfirmed_email' => 'users/confirmations#cancel', as: :user_unconfirmed_email
    get 'users/oauth_sign_up' => 'users/registrations#oauth_new', as: :new_oauth_user_registration
    post 'users/oauth_sign_up' => 'users/registrations#oauth_create', as: :oauth_user_registration
  end
  # google site verification
  get 'google9107c43bb8511ce3' => 'pages#google_site_verification'

  namespace :admin do
    get '/' => 'pages#index'
    resources :service_teams
    resources :service_roles
    resources :service_schedules, except: [:show]
    resources :contacts, except: %i[new create] do
      member do
        post 'handle'
      end
    end
    resources :announcements do
      member do
        post 'post_to_facebook'
      end
    end
    resources :members, only: %i[index show edit update] do
      get 'download', on: :collection
      member do
        post 'become_admin'
        post 'cancel_admin'
      end
    end
    resources :events do
      member do
        get 'download'
      end
      resource :event_users, path: :users
    end
  end
  # sidekiq
  require 'sidekiq/web'
  authenticate :user, ->(u) { Ability.new(u).can?(:manage, :admin) } do
    mount Sidekiq::Web => 'admin/sidekiq'
  end

  # chatbot
  namespace :chatbot do
    post 'line/callback' => 'lines#callback'
    get 'messenger/callback' => 'messengers#verify'
    post 'messenger/callback' => 'messengers#callback'
  end
end

app/controllers/admin/service_schedules_controller.rb
class Admin::ServiceSchedulesController < Admin::BaseController
  before_action :find_schedule, only: [:edit, :update, :destroy]

  def index
    @q = Service::Schedule.ransack(params[:q])
    @schedules = @q.result(distinct: true).includes(:team).order(service_time: :desc).page(params[:page])
  end

  def new
    @schedule = Service::Schedule.new(service_time: Time.now)
  end

  def create
    @schedule = Service::Schedule.new(schedule_params)
    if @schedule.save
      flash[:notice] = t('.success')
      redirect_to admin_service_schedules_url
    else
      flash[:alert] = t('.failed')
      render :new
    end
  end

  def edit; end

  def update
    if @schedule.update(schedule_params)
      flash[:notice] = t('.success')
      redirect_to admin_service_schedules_url
    else
      flash[:alert] = t('.failed')
      render :edit
    end
  end

  def destroy
    if @schedule.destroy
      flash[:notice] = t('.success')
    else
      flash[:alert] = t('.failed')
    end
    redirect_to admin_service_schedules_url
  end

  private
  def schedule_params
    params.require(:service_schedule).permit(:service_team_id, :service_time)
  end

  def find_schedule
    @schedule = Service::Schedule.find params[:id]
  end
end

app/views/admin/service_schedules/_form.html.erb
<%= simple_form_for [:admin, @schedule] do |f| %>
  <%= f.error_notification %>
  <%= f.association :team, collection: Service::Team.all.pluck(:name, :id), prompt: :translate %>
  <%= f.input :service_time %>
  <%= f.button :submit, data: { disable_with: t('.submitting') } %>
<% end %>

app/views/admin/service_schedules/edit.html.erb
<h2><%= t '.title' %>
	<%= link_to t('.back'), :back, class: 'btn btn-outline-secondary' %>
</h2>
<%= render 'form' %>

app/views/admin/service_schedules/index.html.erb
<div class="d-flex flex-row align-items-center justify-content-center flex-wrap">
  <h1><%= t '.title' %></h1>
  <div class="w-100"></div>
  <%= link_to t('.create'), new_admin_service_schedule_path, class: 'btn btn-success ml-auto' %>
</div>
<a class="btn btn-primary my-2" data-toggle="collapse" href="#collapseSearch" aria-expanded="false" aria-controls="collapseSearch"><%= t '.conditions' %></a>
<div class="collapse" id="collapseSearch">
  <div class="card my-2">
    <div class="card-body">
      <%= search_form_for @q, url: admin_service_schedules_url, class: 'form-inline my-2 mx-5' do |f| %>
        <%= f.label Service::Team.human_attribute_name(:name), class: 'mr-1' %>
        <%= f.search_field :team_name_cont, class: 'form-control mr-2' %>
        <div class="w-100 my-1"></div>
        <%= f.label Service::Team.human_attribute_name(:leader), class: 'mr-1' %>
        <%= f.search_field :team_leader_profile_name_cont, class: 'form-control mr-2' %>
        <div class="w-100 my-1"></div>
        <%= link_to t('.clear'), admin_service_schedules_path, class: 'btn btn-outline-secondary ml-auto' %>
        <%= f.button t('.submit'), class: 'btn btn-outline-secondary mx-2 ml-1' %>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @schedules %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th><%= Service::Team.human_attribute_name :name %></th>
      <th><%= Service::Team.human_attribute_name :leader %></th>
      <th><%= Service::Schedule.human_attribute_name :service_time %></th>
      <th><%= t '.more' %></th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= link_to schedule.team.name, admin_service_team_path(schedule.team) %></td>
        <td><%= link_to schedule.team.leader.profile.try(:name), admin_member_path(schedule.team.leader) %></td>
        <td><%= l schedule.service_time %></td>
        <td>
          <%= link_to t('.edit'), edit_admin_service_schedule_path(schedule), class: 'btn btn-warning' %>
          <%= link_to t('.destroy'), admin_service_schedule_path(schedule), class: 'btn btn-danger', method: :delete, data: { confirm: t('.confirm') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @schedules %>

app/views/admin/service_schedules/new.html.erb
<h2><%= t '.title' %>
	<%= link_to t('.back'), admin_service_schedules_path, class: 'btn btn-outline-secondary' %>
</h2>
<%= render 'form' %>