config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :contacts, only: [:create]
  resources :announcements, only: %i[index show]
  resources :events, only: %i[index show] do
    member do
      post 'join'
      post 'quit'
      get 'participants'
    end
  end
  get 'index', 'term', 'about', 'contact', controller: 'pages'
  namespace :account do
    resource :profile, except: [:destroy]
    resource :subscription, only: [:show, :edit, :update]
    resources :messengers, only: [:update]
    resources :events, only: [:index]
  end
  # custom devise controllers
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    delete 'users/unconfirmed_email' => 'users/confirmations#cancel', as: :user_unconfirmed_email
    get 'users/oauth_sign_up' => 'users/registrations#oauth_new', as: :new_oauth_user_registration
    post 'users/oauth_sign_up' => 'users/registrations#oauth_create', as: :oauth_user_registration
  end
  # google site verification
  get 'google9107c43bb8511ce3' => 'pages#google_site_verification'

  namespace :admin do
    get '/' => 'pages#index'
    resources :service_teams
    resources :service_roles
    resources :service_schedules, except: [:show]
    resources :contacts, except: %i[new create] do
      member do
        post 'handle'
      end
    end
    resources :announcements do
      member do
        post 'post_to_facebook'
      end
    end
    resources :members, only: %i[index show edit update] do
      get 'download', on: :collection
      member do
        post 'become_admin'
        post 'cancel_admin'
      end
    end
    resources :events do
      member do
        get 'download'
      end
      resource :event_users, path: :users
    end
  end
  # sidekiq
  require 'sidekiq/web'
  authenticate :user, ->(u) { Ability.new(u).can?(:manage, :admin) } do
    mount Sidekiq::Web => 'admin/sidekiq'
  end

  # chatbot
  namespace :chatbot do
    post 'line/callback' => 'lines#callback'
    get 'messenger/callback' => 'messengers#verify'
    post 'messenger/callback' => 'messengers#callback'
  end
end

app/views/admin/common/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
  <%= link_to admin_path, class: 'navbar-brand' do %>
    <%= image_tag 'brand_white.png', height: 30 %>
    <%= t('.brand') %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto d-sm-none">
      <%= nav_li fa_icon('user-circle', text: User.model_name.human), admin_members_path %>
      <%= nav_li fa_icon('futbol-o', text: Event.model_name.human), admin_events_path %>
      <%= nav_li fa_icon('bullhorn', text: Announcement.model_name.human), admin_announcements_path %>
      <%= nav_li fa_icon('comments', text: Contact.model_name.human), admin_contacts_path %>
    </ul>
    <hr>
    <ul class="navbar-nav mr-auto d-sm-none">
      <%= nav_li fa_icon('users', text: Service::Team.model_name.human), admin_service_teams_path %>
      <%= nav_li fa_icon('user-md', text: Service::Role.model_name.human), admin_service_roles_path %>
      <%= nav_li fa_icon('calendar', text: Service::Schedule.model_name.human), admin_service_schedules_path %>
    </ul>
    <hr>
    <ul class="navbar-nav mr-auto d-sm-none">
      <%= nav_li fa_icon('gear', text: t('.sidekiq')), sidekiq_web_path, target: :_blank %>
    </ul>
    <hr>
    <ul class="navbar-nav ml-auto">
      <%= nav_li fa_icon('sign-out', text: t('.back')), root_path %>
    </ul>
  </div>
</nav>

app/views/admin/common/_sidebar.html.erb
<ul class="nav nav-pills flex-column">
  <%= nav_li fa_icon('user-circle', text: User.model_name.human), admin_members_path %>
  <%= nav_li fa_icon('futbol-o', text: Event.model_name.human), admin_events_path %>
  <%= nav_li fa_icon('bullhorn', text: Announcement.model_name.human), admin_announcements_path %>
  <%= nav_li fa_icon('comments', text: Contact.model_name.human), admin_contacts_path %>
</ul>
<hr>
<ul class="nav nav-pills flex-column">
  <%= nav_li fa_icon('users', text: Service::Team.model_name.human), admin_service_teams_path %>
  <%= nav_li fa_icon('user-md', text: Service::Role.model_name.human), admin_service_roles_path %>
  <%= nav_li fa_icon('calendar', text: Service::Schedule.model_name.human), admin_service_schedules_path %>
</ul>
<hr>
<ul class="nav nav-pills flex-column">
  <%= nav_li fa_icon('gear', text: t('.sidekiq')), sidekiq_web_path, target: :_blank %>
</ul>