config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :contacts, only: [:create]
  resources :announcements, only: %i[index show]
  resources :events, only: %i[index show] do
    member do
      post 'join'
      post 'quit'
      get 'participants'
    end
  end
  get 'index', 'term', 'about', 'contact', controller: 'pages'
  namespace :account do
    resource :profile, except: [:destroy]
    resource :subscription, only: [:show, :edit, :update]
    resources :messengers, only: [:update]
    resources :events, only: [:index]
  end
  # custom devise controllers
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    delete 'users/unconfirmed_email' => 'users/confirmations#cancel', as: :user_unconfirmed_email
    get 'users/oauth_sign_up' => 'users/registrations#oauth_new', as: :new_oauth_user_registration
    post 'users/oauth_sign_up' => 'users/registrations#oauth_create', as: :oauth_user_registration
  end
  # google site verification
  get 'google9107c43bb8511ce3' => 'pages#google_site_verification'

  namespace :admin do
    get '/' => 'pages#index'
    resources :service_teams
    resources :service_roles
    resources :service_schedules, except: [:show]
    resources :contacts, except: %i[new create] do
      member do
        post 'handle'
      end
    end
    resources :announcements do
      member do
        post 'post_to_facebook'
      end
    end
    resources :members, only: %i[index show edit update] do
      get 'download', on: :collection
      member do
        post 'become_admin'
        post 'cancel_admin'
      end
    end
    resources :events do
      member do
        get 'download'
      end
      resource :event_users, path: :users
    end
  end
  # sidekiq
  require 'sidekiq/web'
  authenticate :user, ->(u) { Ability.new(u).can?(:manage, :admin) } do
    mount Sidekiq::Web => 'admin/sidekiq'
  end

  # chatbot
  namespace :chatbot do
    post 'line/callback' => 'lines#callback'
    get 'messenger/callback' => 'messengers#verify'
    post 'messenger/callback' => 'messengers#callback'
  end
end

app/views/common/_footer.html.erb
<footer class="footer bg-light p-2 text-center">
  <div class="container p-2">
    <div class="d-flex flex-wrap align-items-center justify-content-between">
      <h5><%= link_to t('.about'), about_path, class: 'no_ text-dark' %></h5>
      <h5><%= link_to t('.contact'), contact_path, class: 'no_ text-dark' %></h5>
      <h5><%= link_to t('.term'), term_path, class: 'no_ text-dark' %></h5>
      <div class="w-100 d-sm-none"></div>
      <%= link_to t('.my_contact.facebook'), class: 'no_ text-dark' do %>
        <%= fa_stacked_icon "facebook", base: "circle-thin", class: "fa-2x" %>
      <% end %>
      <%= link_to t('.my_contact.youtube'), class: 'no_ text-dark' do %>
        <%= fa_stacked_icon "youtube", base: "circle-thin", class: "fa-2x" %>
      <% end %>
      <%= link_to t('.my_contact.github'), class: 'no_ text-dark' do %>
        <%= fa_stacked_icon "github", base: "circle-thin", class: "fa-2x" %>
      <% end %>
    </div>
    <div class="row mt-2 align-items-center">
      <div class="col-12 col-md-6 text-muted p-2">
        <div><%= t('.my_contact.worship_time') %></div>
        <div><%= t('.my_contact.office_hour') %></div>
      </div>
      <div class="col-12 col-md-6 p-2">
        <div class="lead text-purple"><%= t('.my_contact.tel') %></div>
        <%= mail_to t('.my_contact.email'), t('.my_contact.email'), class: 'no_ text-dark' %>
        <div><%= t('.my_contact.address') %></div>
      </div>
    </div>
  </div>
  © <%= Time.now.year %> Hong Xin Yang.
</footer>

app/views/common/_header.html.erb
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- SEO -->
<meta property="og:type" content="website">
<%= display_meta_tags site: t('.website') %>
<% if Rails.env.production? %>
  <!-- Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GA_TRACK_ID'] %>"></script>
  <script type="text/javascript">
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '<%= ENV['GA_TRACK_ID'] %>');
  </script>
<% end %>
<!-- Rails -->
<%= favicon_link_tag 'favicon.png', type: 'image/png' %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/common/_jumbotron.html.erb
<div class="jumbotron jumbotron-bg my-0">
  <div class="ml-4 mb-4 bg-black-opacity04 d-inline-block p-2 rounded">
    <%= yield :breadcrumb %>
  </div>
  <div class="d-flex justify-content-center">
    <div class="p-5 bg-black-opacity04 rounded">
      <%= yield :jumbotron %>
    </div>
  </div>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <%= image_tag 'brand.png', height: 30 %>
    <%= t('.brand') %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"></ul>
    <ul class="navbar-nav ml-auto">
      <%= nav_li fa_icon('futbol-o', text: Event.model_name.human), events_path %>
      <%= nav_li fa_icon('bullhorn', text: Announcement.model_name.human), announcements_path %>
      <% if user_signed_in? %>
        <%= nav_li(fa_icon('tachometer', text: t('.backstage')), admin_path) if is_admin? %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon('user', text: t('.account._')) %>
            <span class="caret"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to fa_icon('flag', text: t('.account.events')), account_events_path, class: "dropdown-item" %>
            <%= link_to fa_icon('address-card', text: t('.account.profile')), account_profile_path, class: "dropdown-item" %>
            <%= link_to fa_icon('gear', text: t('.account.edit')), edit_user_registration_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to fa_icon('sign-out', text: t('.log_out')), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%= nav_li fa_icon('user-plus', text: t('.sign_up')), new_user_registration_path %>
        <%= nav_li fa_icon('sign-in', text: t('.log_in')), new_user_session_path %>
      <% end %>
    </ul>
  </div>
</nav>